// Generated by gencpp from file ilk_paket/eylem_ornegiFeedback.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_EYLEM_ORNEGIFEEDBACK_H
#define ILK_PAKET_MESSAGE_EYLEM_ORNEGIFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ilk_paket
{
template <class ContainerAllocator>
struct eylem_ornegiFeedback_
{
  typedef eylem_ornegiFeedback_<ContainerAllocator> Type;

  eylem_ornegiFeedback_()
    : hedef_feedback(0)  {
    }
  eylem_ornegiFeedback_(const ContainerAllocator& _alloc)
    : hedef_feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _hedef_feedback_type;
  _hedef_feedback_type hedef_feedback;





  typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct eylem_ornegiFeedback_

typedef ::ilk_paket::eylem_ornegiFeedback_<std::allocator<void> > eylem_ornegiFeedback;

typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiFeedback > eylem_ornegiFeedbackPtr;
typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiFeedback const> eylem_ornegiFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator1> & lhs, const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.hedef_feedback == rhs.hedef_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator1> & lhs, const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ilk_paket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fede99623619730392b156ba69a84c51";
  }

  static const char* value(const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfede996236197303ULL;
  static const uint64_t static_value2 = 0x92b156ba69a84c51ULL;
};

template<class ContainerAllocator>
struct DataType< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilk_paket/eylem_ornegiFeedback";
  }

  static const char* value(const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#geribildirim\n"
"int32 hedef_feedback\n"
;
  }

  static const char* value(const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hedef_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eylem_ornegiFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilk_paket::eylem_ornegiFeedback_<ContainerAllocator>& v)
  {
    s << indent << "hedef_feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hedef_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILK_PAKET_MESSAGE_EYLEM_ORNEGIFEEDBACK_H
