// Generated by gencpp from file ilk_paket/eylem_ornegiActionGoal.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_EYLEM_ORNEGIACTIONGOAL_H
#define ILK_PAKET_MESSAGE_EYLEM_ORNEGIACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <ilk_paket/eylem_ornegiGoal.h>

namespace ilk_paket
{
template <class ContainerAllocator>
struct eylem_ornegiActionGoal_
{
  typedef eylem_ornegiActionGoal_<ContainerAllocator> Type;

  eylem_ornegiActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  eylem_ornegiActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::ilk_paket::eylem_ornegiGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct eylem_ornegiActionGoal_

typedef ::ilk_paket::eylem_ornegiActionGoal_<std::allocator<void> > eylem_ornegiActionGoal;

typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiActionGoal > eylem_ornegiActionGoalPtr;
typedef boost::shared_ptr< ::ilk_paket::eylem_ornegiActionGoal const> eylem_ornegiActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator1> & lhs, const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator1> & lhs, const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ilk_paket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21901762e6658ff184c42dd270bef9e3";
  }

  static const char* value(const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21901762e6658ff1ULL;
  static const uint64_t static_value2 = 0x84c42dd270bef9e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilk_paket/eylem_ornegiActionGoal";
  }

  static const char* value(const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"eylem_ornegiGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ilk_paket/eylem_ornegiGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#hedef\n"
"int32 sinir\n"
"char islem\n"
"float64 a\n"
"float64 b\n"
;
  }

  static const char* value(const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eylem_ornegiActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilk_paket::eylem_ornegiActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::ilk_paket::eylem_ornegiGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILK_PAKET_MESSAGE_EYLEM_ORNEGIACTIONGOAL_H
