// Generated by gencpp from file ilk_paket/servis_ornegi.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_SERVIS_ORNEGI_H
#define ILK_PAKET_MESSAGE_SERVIS_ORNEGI_H

#include <ros/service_traits.h>


#include <ilk_paket/servis_ornegiRequest.h>
#include <ilk_paket/servis_ornegiResponse.h>


namespace ilk_paket
{

struct servis_ornegi
{

typedef servis_ornegiRequest Request;
typedef servis_ornegiResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct servis_ornegi
} // namespace ilk_paket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ilk_paket::servis_ornegi > {
  static const char* value()
  {
    return "23062d1c9d00067c401ffbc6d629d9b9";
  }

  static const char* value(const ::ilk_paket::servis_ornegi&) { return value(); }
};

template<>
struct DataType< ::ilk_paket::servis_ornegi > {
  static const char* value()
  {
    return "ilk_paket/servis_ornegi";
  }

  static const char* value(const ::ilk_paket::servis_ornegi&) { return value(); }
};


// service_traits::MD5Sum< ::ilk_paket::servis_ornegiRequest> should match
// service_traits::MD5Sum< ::ilk_paket::servis_ornegi >
template<>
struct MD5Sum< ::ilk_paket::servis_ornegiRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ilk_paket::servis_ornegi >::value();
  }
  static const char* value(const ::ilk_paket::servis_ornegiRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ilk_paket::servis_ornegiRequest> should match
// service_traits::DataType< ::ilk_paket::servis_ornegi >
template<>
struct DataType< ::ilk_paket::servis_ornegiRequest>
{
  static const char* value()
  {
    return DataType< ::ilk_paket::servis_ornegi >::value();
  }
  static const char* value(const ::ilk_paket::servis_ornegiRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ilk_paket::servis_ornegiResponse> should match
// service_traits::MD5Sum< ::ilk_paket::servis_ornegi >
template<>
struct MD5Sum< ::ilk_paket::servis_ornegiResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ilk_paket::servis_ornegi >::value();
  }
  static const char* value(const ::ilk_paket::servis_ornegiResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ilk_paket::servis_ornegiResponse> should match
// service_traits::DataType< ::ilk_paket::servis_ornegi >
template<>
struct DataType< ::ilk_paket::servis_ornegiResponse>
{
  static const char* value()
  {
    return DataType< ::ilk_paket::servis_ornegi >::value();
  }
  static const char* value(const ::ilk_paket::servis_ornegiResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ILK_PAKET_MESSAGE_SERVIS_ORNEGI_H
