// Generated by gencpp from file ilk_paket/servis_ornegiRequest.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_SERVIS_ORNEGIREQUEST_H
#define ILK_PAKET_MESSAGE_SERVIS_ORNEGIREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ilk_paket
{
template <class ContainerAllocator>
struct servis_ornegiRequest_
{
  typedef servis_ornegiRequest_<ContainerAllocator> Type;

  servis_ornegiRequest_()
    : islem(0)
    , a(0.0)
    , b(0.0)  {
    }
  servis_ornegiRequest_(const ContainerAllocator& _alloc)
    : islem(0)
    , a(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _islem_type;
  _islem_type islem;

   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> const> ConstPtr;

}; // struct servis_ornegiRequest_

typedef ::ilk_paket::servis_ornegiRequest_<std::allocator<void> > servis_ornegiRequest;

typedef boost::shared_ptr< ::ilk_paket::servis_ornegiRequest > servis_ornegiRequestPtr;
typedef boost::shared_ptr< ::ilk_paket::servis_ornegiRequest const> servis_ornegiRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator1> & lhs, const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator2> & rhs)
{
  return lhs.islem == rhs.islem &&
    lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator1> & lhs, const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ilk_paket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8edca533d0b6d1ade3d3de2c528a90bb";
  }

  static const char* value(const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8edca533d0b6d1adULL;
  static const uint64_t static_value2 = 0xe3d3de2c528a90bbULL;
};

template<class ContainerAllocator>
struct DataType< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilk_paket/servis_ornegiRequest";
  }

  static const char* value(const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char islem\n"
"float64 a\n"
"float64 b\n"
;
  }

  static const char* value(const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.islem);
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servis_ornegiRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilk_paket::servis_ornegiRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilk_paket::servis_ornegiRequest_<ContainerAllocator>& v)
  {
    s << indent << "islem: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.islem);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILK_PAKET_MESSAGE_SERVIS_ORNEGIREQUEST_H
