// Auto-generated. Do not edit!

// (in-package ilk_paket.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class eylem_ornegiGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.sinir = null;
      this.islem = null;
      this.a = null;
      this.b = null;
    }
    else {
      if (initObj.hasOwnProperty('sinir')) {
        this.sinir = initObj.sinir
      }
      else {
        this.sinir = 0;
      }
      if (initObj.hasOwnProperty('islem')) {
        this.islem = initObj.islem
      }
      else {
        this.islem = 0;
      }
      if (initObj.hasOwnProperty('a')) {
        this.a = initObj.a
      }
      else {
        this.a = 0.0;
      }
      if (initObj.hasOwnProperty('b')) {
        this.b = initObj.b
      }
      else {
        this.b = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type eylem_ornegiGoal
    // Serialize message field [sinir]
    bufferOffset = _serializer.int32(obj.sinir, buffer, bufferOffset);
    // Serialize message field [islem]
    bufferOffset = _serializer.char(obj.islem, buffer, bufferOffset);
    // Serialize message field [a]
    bufferOffset = _serializer.float64(obj.a, buffer, bufferOffset);
    // Serialize message field [b]
    bufferOffset = _serializer.float64(obj.b, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type eylem_ornegiGoal
    let len;
    let data = new eylem_ornegiGoal(null);
    // Deserialize message field [sinir]
    data.sinir = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [islem]
    data.islem = _deserializer.char(buffer, bufferOffset);
    // Deserialize message field [a]
    data.a = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [b]
    data.b = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 21;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ilk_paket/eylem_ornegiGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5be8905c3eeca2e7c5b767c76d0af813';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #hedef
    int32 sinir
    char islem
    float64 a
    float64 b
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new eylem_ornegiGoal(null);
    if (msg.sinir !== undefined) {
      resolved.sinir = msg.sinir;
    }
    else {
      resolved.sinir = 0
    }

    if (msg.islem !== undefined) {
      resolved.islem = msg.islem;
    }
    else {
      resolved.islem = 0
    }

    if (msg.a !== undefined) {
      resolved.a = msg.a;
    }
    else {
      resolved.a = 0.0
    }

    if (msg.b !== undefined) {
      resolved.b = msg.b;
    }
    else {
      resolved.b = 0.0
    }

    return resolved;
    }
};

module.exports = eylem_ornegiGoal;
