// Auto-generated. Do not edit!

// (in-package ilk_paket.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class eylem_ornegiResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.sonuc = null;
    }
    else {
      if (initObj.hasOwnProperty('sonuc')) {
        this.sonuc = initObj.sonuc
      }
      else {
        this.sonuc = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type eylem_ornegiResult
    // Serialize message field [sonuc]
    bufferOffset = _serializer.float32(obj.sonuc, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type eylem_ornegiResult
    let len;
    let data = new eylem_ornegiResult(null);
    // Deserialize message field [sonuc]
    data.sonuc = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ilk_paket/eylem_ornegiResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fb68b3109d1a03c44153510bb38b9ace';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #sonuc
    float32 sonuc
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new eylem_ornegiResult(null);
    if (msg.sonuc !== undefined) {
      resolved.sonuc = msg.sonuc;
    }
    else {
      resolved.sonuc = 0.0
    }

    return resolved;
    }
};

module.exports = eylem_ornegiResult;
