// Auto-generated. Do not edit!

// (in-package ilk_paket.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class eylem_ornegiFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.hedef_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('hedef_feedback')) {
        this.hedef_feedback = initObj.hedef_feedback
      }
      else {
        this.hedef_feedback = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type eylem_ornegiFeedback
    // Serialize message field [hedef_feedback]
    bufferOffset = _serializer.int32(obj.hedef_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type eylem_ornegiFeedback
    let len;
    let data = new eylem_ornegiFeedback(null);
    // Deserialize message field [hedef_feedback]
    data.hedef_feedback = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ilk_paket/eylem_ornegiFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fede99623619730392b156ba69a84c51';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #geribildirim
    int32 hedef_feedback
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new eylem_ornegiFeedback(null);
    if (msg.hedef_feedback !== undefined) {
      resolved.hedef_feedback = msg.hedef_feedback;
    }
    else {
      resolved.hedef_feedback = 0
    }

    return resolved;
    }
};

module.exports = eylem_ornegiFeedback;
