; Auto-generated. Do not edit!


(cl:in-package ilk_paket-msg)


;//! \htmlinclude eylem_ornegiResult.msg.html

(cl:defclass <eylem_ornegiResult> (roslisp-msg-protocol:ros-message)
  ((sonuc
    :reader sonuc
    :initarg :sonuc
    :type cl:float
    :initform 0.0))
)

(cl:defclass eylem_ornegiResult (<eylem_ornegiResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <eylem_ornegiResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'eylem_ornegiResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ilk_paket-msg:<eylem_ornegiResult> is deprecated: use ilk_paket-msg:eylem_ornegiResult instead.")))

(cl:ensure-generic-function 'sonuc-val :lambda-list '(m))
(cl:defmethod sonuc-val ((m <eylem_ornegiResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ilk_paket-msg:sonuc-val is deprecated.  Use ilk_paket-msg:sonuc instead.")
  (sonuc m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <eylem_ornegiResult>) ostream)
  "Serializes a message object of type '<eylem_ornegiResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'sonuc))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <eylem_ornegiResult>) istream)
  "Deserializes a message object of type '<eylem_ornegiResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'sonuc) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<eylem_ornegiResult>)))
  "Returns string type for a message object of type '<eylem_ornegiResult>"
  "ilk_paket/eylem_ornegiResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'eylem_ornegiResult)))
  "Returns string type for a message object of type 'eylem_ornegiResult"
  "ilk_paket/eylem_ornegiResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<eylem_ornegiResult>)))
  "Returns md5sum for a message object of type '<eylem_ornegiResult>"
  "fb68b3109d1a03c44153510bb38b9ace")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'eylem_ornegiResult)))
  "Returns md5sum for a message object of type 'eylem_ornegiResult"
  "fb68b3109d1a03c44153510bb38b9ace")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<eylem_ornegiResult>)))
  "Returns full string definition for message of type '<eylem_ornegiResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#sonuc~%float32 sonuc~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'eylem_ornegiResult)))
  "Returns full string definition for message of type 'eylem_ornegiResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#sonuc~%float32 sonuc~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <eylem_ornegiResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <eylem_ornegiResult>))
  "Converts a ROS message object to a list"
  (cl:list 'eylem_ornegiResult
    (cl:cons ':sonuc (sonuc msg))
))
