; Auto-generated. Do not edit!


(cl:in-package ilk_paket-msg)


;//! \htmlinclude eylem_ornegiFeedback.msg.html

(cl:defclass <eylem_ornegiFeedback> (roslisp-msg-protocol:ros-message)
  ((hedef_feedback
    :reader hedef_feedback
    :initarg :hedef_feedback
    :type cl:integer
    :initform 0))
)

(cl:defclass eylem_ornegiFeedback (<eylem_ornegiFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <eylem_ornegiFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'eylem_ornegiFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ilk_paket-msg:<eylem_ornegiFeedback> is deprecated: use ilk_paket-msg:eylem_ornegiFeedback instead.")))

(cl:ensure-generic-function 'hedef_feedback-val :lambda-list '(m))
(cl:defmethod hedef_feedback-val ((m <eylem_ornegiFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ilk_paket-msg:hedef_feedback-val is deprecated.  Use ilk_paket-msg:hedef_feedback instead.")
  (hedef_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <eylem_ornegiFeedback>) ostream)
  "Serializes a message object of type '<eylem_ornegiFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'hedef_feedback)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <eylem_ornegiFeedback>) istream)
  "Deserializes a message object of type '<eylem_ornegiFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'hedef_feedback) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<eylem_ornegiFeedback>)))
  "Returns string type for a message object of type '<eylem_ornegiFeedback>"
  "ilk_paket/eylem_ornegiFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'eylem_ornegiFeedback)))
  "Returns string type for a message object of type 'eylem_ornegiFeedback"
  "ilk_paket/eylem_ornegiFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<eylem_ornegiFeedback>)))
  "Returns md5sum for a message object of type '<eylem_ornegiFeedback>"
  "fede99623619730392b156ba69a84c51")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'eylem_ornegiFeedback)))
  "Returns md5sum for a message object of type 'eylem_ornegiFeedback"
  "fede99623619730392b156ba69a84c51")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<eylem_ornegiFeedback>)))
  "Returns full string definition for message of type '<eylem_ornegiFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#geribildirim~%int32 hedef_feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'eylem_ornegiFeedback)))
  "Returns full string definition for message of type 'eylem_ornegiFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#geribildirim~%int32 hedef_feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <eylem_ornegiFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <eylem_ornegiFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'eylem_ornegiFeedback
    (cl:cons ':hedef_feedback (hedef_feedback msg))
))
